# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/xdc/system.xdc

# Block Designs: bd/system/system.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_axis_passthrough_mon_0_0/system_axis_passthrough_mon_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axis_passthrough_mon_0_0 || ORIG_REF_NAME==system_axis_passthrough_mon_0_0} -quiet] -quiet

# IP: bd/system/ip/system_v_tpg_0_0/system_v_tpg_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_v_tpg_0_0 || ORIG_REF_NAME==system_v_tpg_0_0} -quiet] -quiet

# IP: bd/system/ip/system_AXI_LITE_REG_0_0/system_AXI_LITE_REG_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_AXI_LITE_REG_0_0 || ORIG_REF_NAME==system_AXI_LITE_REG_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_uartlite_0_0/system_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_uartlite_0_0 || ORIG_REF_NAME==system_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_ps8_0_300M_0/system_rst_ps8_0_300M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_ps8_0_300M_0 || ORIG_REF_NAME==system_rst_ps8_0_300M_0} -quiet] -quiet

# IP: bd/system/ip/system_xlconcat_0_0/system_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconcat_0_0 || ORIG_REF_NAME==system_xlconcat_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xlconstant_0_0/system_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconstant_0_0 || ORIG_REF_NAME==system_xlconstant_0_0} -quiet] -quiet

# IP: bd/system/ip/system_zynq_ultra_ps_e_0_0/system_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==system_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_vdma_0_0 || ORIG_REF_NAME==system_axi_vdma_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_vdma_1_0/system_axi_vdma_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_vdma_1_0 || ORIG_REF_NAME==system_axi_vdma_1_0} -quiet] -quiet

# IP: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_video_clk_wiz_0/system_rst_video_clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_video_clk_wiz_0 || ORIG_REF_NAME==system_rst_video_clk_wiz_0} -quiet] -quiet

# IP: bd/system/ip/system_v_axi4s_vid_out_0_0/system_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==system_v_axi4s_vid_out_0_0} -quiet] -quiet

# IP: bd/system/ip/system_v_tc_0_0/system_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_v_tc_0_0 || ORIG_REF_NAME==system_v_tc_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xlconstant_0_1/system_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconstant_0_1 || ORIG_REF_NAME==system_xlconstant_0_1} -quiet] -quiet

# IP: bd/system/ip/system_axis_switch_0_3/system_axis_switch_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axis_switch_0_3 || ORIG_REF_NAME==system_axis_switch_0_3} -quiet] -quiet

# IP: bd/system/ip/system_v_tpg_0_6/system_v_tpg_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_v_tpg_0_6 || ORIG_REF_NAME==system_v_tpg_0_6} -quiet] -quiet

# IP: bd/system/ip/system_xbar_4/system_xbar_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xbar_4 || ORIG_REF_NAME==system_xbar_4} -quiet] -quiet

# IP: bd/system/ip/system_ps8_0_axi_periph_3/system_ps8_0_axi_periph_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_ps8_0_axi_periph_3 || ORIG_REF_NAME==system_ps8_0_axi_periph_3} -quiet] -quiet

# IP: bd/system/ip/system_axi_vdma_3_0/system_axi_vdma_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_vdma_3_0 || ORIG_REF_NAME==system_axi_vdma_3_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_smc_0/system_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axi_smc_0 || ORIG_REF_NAME==system_axi_smc_0} -quiet] -quiet

# IP: bd/system/ip/system_xlconstant_0_2/system_xlconstant_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconstant_0_2 || ORIG_REF_NAME==system_xlconstant_0_2} -quiet] -quiet

# IP: bd/system/ip/system_axis_passthrough_mon_0_7/system_axis_passthrough_mon_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axis_passthrough_mon_0_7 || ORIG_REF_NAME==system_axis_passthrough_mon_0_7} -quiet] -quiet

# IP: bd/system/ip/system_rst_video_clk_wiz_1/system_rst_video_clk_wiz_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_video_clk_wiz_1 || ORIG_REF_NAME==system_rst_video_clk_wiz_1} -quiet] -quiet

# IP: bd/system/ip/system_v_axi4s_vid_out_0_1/system_v_axi4s_vid_out_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_v_axi4s_vid_out_0_1 || ORIG_REF_NAME==system_v_axi4s_vid_out_0_1} -quiet] -quiet

# IP: bd/system/ip/system_v_tc_0_1/system_v_tc_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_v_tc_0_1 || ORIG_REF_NAME==system_v_tc_0_1} -quiet] -quiet

# IP: bd/system/ip/system_xlconstant_0_3/system_xlconstant_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconstant_0_3 || ORIG_REF_NAME==system_xlconstant_0_3} -quiet] -quiet

# IP: bd/system/ip/system_v_vid_in_axi4s_0_0/system_v_vid_in_axi4s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==system_v_vid_in_axi4s_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axis_passthrough_mon_0_8/system_axis_passthrough_mon_0_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axis_passthrough_mon_0_8 || ORIG_REF_NAME==system_axis_passthrough_mon_0_8} -quiet] -quiet

# IP: bd/system/ip/system_v_tpg_0_8/system_v_tpg_0_8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_v_tpg_0_8 || ORIG_REF_NAME==system_v_tpg_0_8} -quiet] -quiet

# IP: bd/system/ip/system_axis_switch_0_5/system_axis_switch_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axis_switch_0_5 || ORIG_REF_NAME==system_axis_switch_0_5} -quiet] -quiet

# IP: bd/system/ip/system_v_tpg_1_1/system_v_tpg_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_v_tpg_1_1 || ORIG_REF_NAME==system_v_tpg_1_1} -quiet] -quiet

# IP: bd/system/ip/system_rst_video_clk_wiz_2/system_rst_video_clk_wiz_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_rst_video_clk_wiz_2 || ORIG_REF_NAME==system_rst_video_clk_wiz_2} -quiet] -quiet

# IP: bd/system/ip/system_v_axi4s_vid_out_0_2/system_v_axi4s_vid_out_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_v_axi4s_vid_out_0_2 || ORIG_REF_NAME==system_v_axi4s_vid_out_0_2} -quiet] -quiet

# IP: bd/system/ip/system_v_tc_0_2/system_v_tc_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_v_tc_0_2 || ORIG_REF_NAME==system_v_tc_0_2} -quiet] -quiet

# IP: bd/system/ip/system_xlconstant_0_4/system_xlconstant_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_xlconstant_0_4 || ORIG_REF_NAME==system_xlconstant_0_4} -quiet] -quiet

# IP: bd/system/ip/system_v_vid_in_axi4s_0_1/system_v_vid_in_axi4s_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_v_vid_in_axi4s_0_1 || ORIG_REF_NAME==system_v_vid_in_axi4s_0_1} -quiet] -quiet

# IP: bd/system/ip/system_tier2_xbar_0_0/system_tier2_xbar_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_tier2_xbar_0_0 || ORIG_REF_NAME==system_tier2_xbar_0_0} -quiet] -quiet

# IP: bd/system/ip/system_tier2_xbar_1_0/system_tier2_xbar_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_tier2_xbar_1_0 || ORIG_REF_NAME==system_tier2_xbar_1_0} -quiet] -quiet

# IP: bd/system/ip/system_tier2_xbar_2_0/system_tier2_xbar_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_tier2_xbar_2_0 || ORIG_REF_NAME==system_tier2_xbar_2_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0} -quiet] -quiet

# XDC: bd/system/system_ooc.xdc
