# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/txzing/Desktop/1_FPGA_Design/MPSoC_XCZU4EV_FPGA/XCZU4EV/23_ov5640_udp_pc/ov5640_udp_pc.srcs/sources_1/ip/async_fifo_1024x32b/async_fifo_1024x32b.xci
# IP: The module: 'async_fifo_1024x32b' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/txzing/Desktop/1_FPGA_Design/MPSoC_XCZU4EV_FPGA/XCZU4EV/23_ov5640_udp_pc/ov5640_udp_pc.srcs/sources_1/ip/async_fifo_1024x32b/async_fifo_1024x32b.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_fifo_1024x32b'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/txzing/Desktop/1_FPGA_Design/MPSoC_XCZU4EV_FPGA/XCZU4EV/23_ov5640_udp_pc/ov5640_udp_pc.srcs/sources_1/ip/async_fifo_1024x32b/async_fifo_1024x32b_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_fifo_1024x32b'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/txzing/Desktop/1_FPGA_Design/MPSoC_XCZU4EV_FPGA/XCZU4EV/23_ov5640_udp_pc/ov5640_udp_pc.srcs/sources_1/ip/async_fifo_1024x32b/async_fifo_1024x32b_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_fifo_1024x32b'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/txzing/Desktop/1_FPGA_Design/MPSoC_XCZU4EV_FPGA/XCZU4EV/23_ov5640_udp_pc/ov5640_udp_pc.srcs/sources_1/ip/async_fifo_1024x32b/async_fifo_1024x32b.xci
# IP: The module: 'async_fifo_1024x32b' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/txzing/Desktop/1_FPGA_Design/MPSoC_XCZU4EV_FPGA/XCZU4EV/23_ov5640_udp_pc/ov5640_udp_pc.srcs/sources_1/ip/async_fifo_1024x32b/async_fifo_1024x32b.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_fifo_1024x32b'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/txzing/Desktop/1_FPGA_Design/MPSoC_XCZU4EV_FPGA/XCZU4EV/23_ov5640_udp_pc/ov5640_udp_pc.srcs/sources_1/ip/async_fifo_1024x32b/async_fifo_1024x32b_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_fifo_1024x32b'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/txzing/Desktop/1_FPGA_Design/MPSoC_XCZU4EV_FPGA/XCZU4EV/23_ov5640_udp_pc/ov5640_udp_pc.srcs/sources_1/ip/async_fifo_1024x32b/async_fifo_1024x32b_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_fifo_1024x32b'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
