
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2020.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2022 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xvtc.h"

/*
* The configuration table for devices
*/

XVtc_Config XVtc_ConfigTable[XPAR_XVTC_NUM_INSTANCES] =
{
	{
		XPAR_CH_0_V_TC_0_DEVICE_ID,
		XPAR_CH_0_V_TC_0_BASEADDR
	},
	{
		XPAR_CH_1_V_TC_0_DEVICE_ID,
		XPAR_CH_1_V_TC_0_BASEADDR
	},
	{
		XPAR_VID_OUT_SS_V_TC_0_DEVICE_ID,
		XPAR_VID_OUT_SS_V_TC_0_BASEADDR
	}
};


