# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/workdir/pic_lwip_udp/video_mix/vivado/vivado_proj/vivado_proj.srcs/sources_1/bd/system/ip/system_v_tpg_0_6/system_v_tpg_0_6.xci
# IP: The module: 'system_v_tpg_0_6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/workdir/pic_lwip_udp/video_mix/vivado/vivado_proj/vivado_proj.srcs/sources_1/bd/system/ip/system_v_tpg_0_6/system_v_tpg_0_6.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_v_tpg_0_6'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/workdir/pic_lwip_udp/video_mix/vivado/vivado_proj/vivado_proj.srcs/sources_1/bd/system/ip/system_v_tpg_0_6/system_v_tpg_0_6_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_v_tpg_0_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/workdir/pic_lwip_udp/video_mix/vivado/vivado_proj/vivado_proj.srcs/sources_1/bd/system/ip/system_v_tpg_0_6/system_v_tpg_0_6.xci
# IP: The module: 'system_v_tpg_0_6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/workdir/pic_lwip_udp/video_mix/vivado/vivado_proj/vivado_proj.srcs/sources_1/bd/system/ip/system_v_tpg_0_6/system_v_tpg_0_6.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_v_tpg_0_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/workdir/pic_lwip_udp/video_mix/vivado/vivado_proj/vivado_proj.srcs/sources_1/bd/system/ip/system_v_tpg_0_6/system_v_tpg_0_6_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_v_tpg_0_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
