# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/workdir/pic_lwip_udp/video_mix/vivado/vivado_proj/vivado_proj.srcs/sources_1/bd/system/ip/system_axis_switch_0_5/system_axis_switch_0_5.xci
# IP: The module: 'system_axis_switch_0_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/workdir/pic_lwip_udp/video_mix/vivado/vivado_proj/vivado_proj.srcs/sources_1/bd/system/ip/system_axis_switch_0_5/system_axis_switch_0_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axis_switch_0_5'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/workdir/pic_lwip_udp/video_mix/vivado/vivado_proj/vivado_proj.srcs/sources_1/bd/system/ip/system_axis_switch_0_5/system_axis_switch_0_5.xci
# IP: The module: 'system_axis_switch_0_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/workdir/pic_lwip_udp/video_mix/vivado/vivado_proj/vivado_proj.srcs/sources_1/bd/system/ip/system_axis_switch_0_5/system_axis_switch_0_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axis_switch_0_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
